# Generated by Django 3.2.7 on 2021-09-18 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('admins', 'user_system')]},
        ),
    ]
