# Generated by Django 3.2.7 on 2021-09-21 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_user_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('user_public', 'user default acess')]},
        ),
    ]
