# Generated by Django 3.2.7 on 2021-11-27 02:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vacina',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vacina_type', models.CharField(choices=[('Outra', 'Sem indentificação'), ('Pfizer', 'pfizer'), ('Astrazenica', 'astra'), ('CoronaVAC', 'coronavac'), ('Febre Amarela', 'fba'), ('Girpe', 'gripe')], default=('Outra', 'Sem indentificação'), max_length=30)),
            ],
        ),
    ]
