# Generated by Django 3.2.7 on 2021-11-29 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacina', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacina',
            name='vacina_type',
            field=models.CharField(choices=[('Outra', 'Sem indentificação'), ('Pfizer', 'pfizer'), ('Astrazenica', 'astra'), ('CoronaVAC', 'coronavac'), ('Febre Amarela', 'fba'), ('Girpe', 'gripe')], max_length=30),
        ),
    ]
