# Generated by Django 3.2.7 on 2021-11-27 02:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vacina', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data')),
                ('data_visita', models.DateTimeField()),
                ('obs', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[(1, 'Concuildo'), (2, 'Agendado'), (3, 'Cancelado')], default=2, max_length=10)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('vacina', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='vacina.vacina')),
            ],
        ),
    ]
