# Generated by Django 3.2.7 on 2021-11-27 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='status',
            field=models.CharField(choices=[('1', 'Concuildo'), ('2', 'Agendado'), ('3', 'Cancelado'), ('4', 'Em Analise')], default=('4', 'Em Analise'), max_length=10),
        ),
    ]
