# Generated by Django 3.2.7 on 2021-11-27 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0002_alter_agendamento_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='data_visita',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
