# Generated by Django 3.2.7 on 2021-11-30 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20211130_1202'),
        ('vacina', '0002_alter_vacina_vacina_type'),
        ('agendamento', '0003_alter_agendamento_data_visita'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='endreco_visita',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='user.endereco'),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='vacina',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='vacina.vacina'),
        ),
    ]
